Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x10000c33f[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x100013c6f[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004cb1a7[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004cb367[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004f9713[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004f981f[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004f9b47[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004fa4b3[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004f985b[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x10052283f[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1005234c3[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x10052499f[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x1004f9897[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x10052d2d7[0m
[2m  Binary file "[0m[1m[35m$DIR/src/bin/lpython[39m[0m[2m", local address: 0x10053087b[0m
AssertFailed: x.n_head == 1
